--- #YAML:1.0
name:               PBS-Client
version:            0.11
abstract:           Perl interface to submit jobs to Portable Batch System (PBS).
author:
    - Ka-Wai Mak
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  2.121
    File::Temp:    0.14
    IPC::Open3:    1.02
    Symbol:        1.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
